// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LimsProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317232446_AddLabAnalysis")]
    partial class AddLabAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvarageTemperature")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CbdPercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentMoisture")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CurrentTemperature")
                        .HasColumnType("numeric");

                    b.Property<bool>("HasContaminants")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Strain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ThcPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("LimsProject.Models.LabAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CBD")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("THC")
                        .HasColumnType("numeric");

                    b.Property<string>("Terpenes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LabAnalyses");
                });

            modelBuilder.Entity("LimsProject.Models.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SensorData");
                });
#pragma warning restore 612, 618
        }
    }
}
