// <auto-generated />
using System;
using LimsProject.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LimsProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506201129_AddSeedToSaleEntities")]
    partial class AddSeedToSaleEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LimsProject.Features.Batches.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SeedLotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeedLotId");

                    b.HasIndex("Status");

                    b.ToTable("Batches", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Genetics.Strain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHemp")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("ThcMaxLimit")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Strains", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Harvest.HarvestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WetWeightGrams")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("HarvestRecords", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.LabAnalysis.LabAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cbd")
                        .HasColumnType("numeric")
                        .HasColumnName("CBD");

                    b.Property<bool>("HasContaminants")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MoisturePercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("Terpenes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("Thc")
                        .HasColumnType("numeric")
                        .HasColumnName("THC");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("LabAnalyses", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Packaging.FinishedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("StrainId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitWeightGrams")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("StrainId");

                    b.ToTable("FinishedProducts", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Packaging.ProductPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FinishedProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PackagedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("WeightGrams")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("FinishedProductId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("ProductPackages", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Plants.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotherPlantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TagCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("TagCode")
                        .IsUnique();

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.PostHarvest.CuringRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DryingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalMoisture")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DryingId");

                    b.ToTable("CuringRecords", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.PostHarvest.DryingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DryWeightGrams")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HarvestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.ToTable("DryingRecords", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.SeedLots.SeedLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StrainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("StrainId", "LotCode")
                        .IsUnique();

                    b.ToTable("SeedLots", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.Alerts.AlertThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaxHumidity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxTemperature")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinTemperature")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StrainId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrainId");

                    b.ToTable("AlertThresholds", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.Alerts.EnvironmentalAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SensorDataId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Resolved");

                    b.ToTable("EnvironmentalAlerts", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.Rollup.BatchDailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgTemperature")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Date")
                        .IsUnique();

                    b.ToTable("BatchesDailySumaries", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Co2")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SensorType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "ReadingTime");

                    b.ToTable("SensorData", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Traceability.ChainOfCustodyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "OccurredAt");

                    b.ToTable("ChainOfCustodyEvents", (string)null);
                });

            modelBuilder.Entity("LimsProject.Features.Batches.Batch", b =>
                {
                    b.HasOne("LimsProject.Features.SeedLots.SeedLot", null)
                        .WithMany()
                        .HasForeignKey("SeedLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Harvest.HarvestRecord", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.LabAnalysis.LabAnalysis", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Packaging.FinishedProduct", b =>
                {
                    b.HasOne("LimsProject.Features.Genetics.Strain", null)
                        .WithMany()
                        .HasForeignKey("StrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Packaging.ProductPackage", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LimsProject.Features.Packaging.FinishedProduct", null)
                        .WithMany()
                        .HasForeignKey("FinishedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Plants.Plant", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.PostHarvest.CuringRecord", b =>
                {
                    b.HasOne("LimsProject.Features.PostHarvest.DryingRecord", null)
                        .WithMany()
                        .HasForeignKey("DryingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.PostHarvest.DryingRecord", b =>
                {
                    b.HasOne("LimsProject.Features.Harvest.HarvestRecord", null)
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.SeedLots.SeedLot", b =>
                {
                    b.HasOne("LimsProject.Features.Genetics.Strain", null)
                        .WithMany()
                        .HasForeignKey("StrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.Alerts.AlertThreshold", b =>
                {
                    b.HasOne("LimsProject.Features.Genetics.Strain", null)
                        .WithMany()
                        .HasForeignKey("StrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.Alerts.EnvironmentalAlert", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.Rollup.BatchDailySummary", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Sensors.SensorData", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LimsProject.Features.Traceability.ChainOfCustodyEvent", b =>
                {
                    b.HasOne("LimsProject.Features.Batches.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
